if(false){
(function(){'use strict';
var csrf='',view='overview',cache={};
var $=function(s,r){return(r||document).querySelector(s)};
var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})};
function api(path,options){options=options||{};options.headers=Object.assign({'Accept':'application/json'},options.headers||{});if(options.method&&options.method!=='GET')options.headers['X-CSRF-Token']=csrf;return fetch('/admin/api/'+path,options).then(function(r){return r.json().catch(function(){return{ok:false,error:'Invalid server response'}}).then(function(b){if(r.status===401){showLogin();throw new Error('Session expired')}if(!r.ok||!b.ok)throw new Error(b.error||'Request failed');return b})})}
function post(path,data){return api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data||{})})}
function note(msg,bad){var n=$('#notice');n.textContent=msg;n.hidden=false;n.classList.toggle('is-error',!!bad);clearTimeout(n._t);n._t=setTimeout(function(){n.hidden=true},3500)}
function showLogin(){$('#dashboard').hidden=true;$('#login').hidden=false;csrf=''}
function showDash(){$('#login').hidden=true;$('#dashboard').hidden=false;openView(view)}
$('#login-form').addEventListener('submit',function(e){e.preventDefault();var err=$('#login-error');err.hidden=true;fetch('/admin/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#password').value})}).then(function(r){return r.json().then(function(b){if(!r.ok)throw new Error(b.error==='dashboard_not_configured'?'Set ADMIN_DASHBOARD_PASSWORD on the server first.':'Incorrect password or too many attempts.');csrf=b.csrf;$('#password').value='';showDash()})}).catch(function(x){err.textContent=x.message;err.hidden=false})});
$('#logout').addEventListener('click',function(){post('logout',{}).finally(showLogin)});
$('#nav').addEventListener('click',function(e){var b=e.target.closest('[data-view]');if(!b)return;view=b.dataset.view;openView(view)});
function setNav(){document.querySelectorAll('[data-view]').forEach(function(b){b.classList.toggle('is-active',b.dataset.view===view)});$('#title').textContent={overview:'Overview',jobs:'Vacancies',applications:'Applications',reviews:'Reviews',images:'Hero images'}[view];var a=$('#primary-action');a.hidden=view!=='jobs';a.textContent='+ New vacancy';a.onclick=function(){editJob()}}
function openView(name){setNav();$('#content').innerHTML='<div class="empty">Loading…</div>';if(name==='overview')return loadOverview();api(name).then(function(r){cache[name]=r.data;renderList(name,r.data)}).catch(function(e){note(e.message,true)})}
function loadOverview(){Promise.all([api('summary'),api('jobs'),api('applications'),api('reviews')]).then(function(all){var s=all[0].data;cache.jobs=all[1].data;cache.applications=all[2].data;cache.reviews=all[3].data;$('#content').innerHTML='<div class="cards">'+metric(s.liveJobs,'Live vacancies',s.jobs-s.liveJobs+' drafts')+metric(s.pendingApplications,'New applications',s.applications+' total')+metric(s.pendingReviews,'Reviews awaiting approval',s.reviews+' total')+metric(s.liveImages,'Live hero images',s.images+' total')+'</div><section class="panel"><div class="panel__head"><h2>Recent applications</h2></div>'+appsTable(cache.applications.slice(0,6))+'</section>'}).catch(function(e){note(e.message,true)})}
function metric(n,label,sub){return'<article class="metric"><strong>'+esc(n)+'</strong><span>'+esc(label)+'</span><small class="sub">'+esc(sub)+'</small></article>'}
function renderList(name,rows){var search='<div class="toolbar"><input class="search" id="search" placeholder="Search '+esc(name)+'…"></div>';var body=name==='jobs'?jobsTable(rows):name==='applications'?appsTable(rows):name==='reviews'?reviewsTable(rows):imagesTable(rows);$('#content').innerHTML=search+'<section class="panel">'+body+'</section>';$('#search').addEventListener('input',function(){var q=this.value.toLowerCase();var filtered=rows.filter(function(x){return JSON.stringify(x).toLowerCase().indexOf(q)!==-1});$('.panel').innerHTML=name==='jobs'?jobsTable(filtered):name==='applications'?appsTable(filtered):name==='reviews'?reviewsTable(filtered):imagesTable(filtered)})}
function table(head,rows){return'<div class="table-wrap"><table class="table"><thead><tr>'+head.map(function(x){return'<th>'+x+'</th>'}).join('')+'</tr></thead><tbody>'+rows+'</tbody></table></div>'}
function jobsTable(rows){if(!rows.length)return'<div class="empty">No vacancies found.</div>';return table(['Vacancy','Location','Status','Actions'],rows.map(function(j){return'<tr><td><strong>'+esc(j.title)+'</strong><span class="sub">'+esc(j.id)+' · '+esc(j.salary)+'</span></td><td>'+esc(j.city)+', '+esc(j.country)+'<span class="sub">'+esc(j.category)+'</span></td><td><span class="pill '+(j.published?'':'pill--off')+'">'+(j.published?'Live':'Draft')+'</span></td><td class="actions"><button data-action="edit" data-id="'+esc(j.id)+'">Edit</button><button data-action="toggle" data-id="'+esc(j.id)+'">'+(j.published?'Unpublish':'Publish')+'</button><button class="danger" data-action="delete" data-id="'+esc(j.id)+'">Delete</button></td></tr>'}).join(''))}
function appsTable(rows){if(!rows.length)return'<div class="empty">No applications yet.</div>';return table(['Applicant','Job','Details','Actions'],rows.map(function(a){var ans=a.answers||{};var details=Object.keys(ans).filter(function(k){return !/^data:image/.test(String(ans[k]))}).slice(0,30).map(function(k){return'<dt>'+esc(k.replace(/([A-Z])/g,' $1'))+'</dt><dd>'+esc(Array.isArray(ans[k])?ans[k].join(', '):ans[k])+'</dd>'}).join('');return'<tr><td><strong>'+esc(ans.fullName||a.id)+'</strong><span class="sub">'+esc(a.id)+' · '+esc(a.received)+'</span></td><td>'+esc(a.jobTitle||'Open application')+'<span class="sub">'+esc(a.jobCity||'')+' '+esc(a.jobCountry||'')+'</span></td><td><details class="detail"><summary>View application</summary><dl>'+details+'</dl><span class="sub">Photos: '+esc((a.photoSlots||[]).join(', ')||'none')+'</span></details></td><td class="actions"><button data-action="app-toggle" data-id="'+esc(a.id)+'">'+(a.converted?'Mark new':'Mark handled')+'</button><button class="danger" data-action="app-delete" data-id="'+esc(a.id)+'">Delete</button></td></tr>'}).join(''))}
function reviewsTable(rows){if(!rows.length)return'<div class="empty">No reviews yet.</div>';return table(['Reviewer','Review','Status','Actions'],rows.map(function(r){return'<tr><td><strong>'+esc(r.name)+'</strong><span class="sub">'+esc(r.id)+' · '+esc(r.rating)+'/5</span></td><td class="detail">'+esc(r.text)+'</td><td><span class="pill '+(r.published?'':'pill--off')+'">'+(r.published?'Published':'Pending')+'</span></td><td class="actions"><button data-action="review-toggle" data-id="'+esc(r.id)+'" data-published="'+r.published+'">'+(r.published?'Hide':'Publish')+'</button><button class="danger" data-action="review-delete" data-id="'+esc(r.id)+'">Delete</button></td></tr>'}).join(''))}
function imagesTable(rows){if(!rows.length)return'<div class="empty">No bot-managed hero images. The bundled homepage images remain active.</div>';return table(['Image','ID','Status','Actions'],rows.map(function(r){var src=r.file?'media/'+r.file:'';return'<tr><td>'+(src?'<img class="thumb" src="/'+esc(src)+'" alt="">':'—')+'</td><td>'+esc(r.id)+'</td><td><span class="pill '+(r.published===false?'pill--off':'')+'">'+(r.published===false?'Hidden':'Live')+'</span></td><td class="actions"><button data-action="image-toggle" data-id="'+esc(r.id)+'">'+(r.published===false?'Show':'Hide')+'</button><button class="danger" data-action="image-delete" data-id="'+esc(r.id)+'">Delete</button></td></tr>'}).join(''))}
$('#content').addEventListener('click',function(e){var b=e.target.closest('[data-action]');if(!b)return;var id=b.dataset.id,a=b.dataset.action;if(a==='edit')return editJob((cache.jobs||[]).find(function(x){return x.id===id}));if(a.indexOf('delete')!==-1&&!confirm('Delete '+id+' permanently? This cannot be undone.'))return;var map={toggle:'jobs/toggle',delete:'jobs/delete','app-toggle':'applications/toggle','app-delete':'applications/delete','review-toggle':'reviews/toggle','review-delete':'reviews/delete','image-toggle':'images/toggle','image-delete':'images/delete'};post(map[a],{id:id,published:b.dataset.published==='true'}).then(function(){note('Saved');openView(view)}).catch(function(x){note(x.message,true)})});
var dlg=$('#job-dialog'),form=$('#job-form');function editJob(job){job=job||{};$('#job-heading').textContent=job.id?'Edit '+job.id:'New vacancy';['id','title','country','city','region','category','salary','salaryUsd','hours','type','desc'].forEach(function(k){if(form.elements[k])form.elements[k].value=job[k]==null?'':job[k]});form.elements.tags.value=(job.tags||[]).join(', ');form.elements.published.checked=job.id?!!job.published:true;dlg.showModal()}document.querySelectorAll('[data-close]').forEach(function(b){b.addEventListener('click',function(){dlg.close()})});form.addEventListener('submit',function(e){e.preventDefault();var d=Object.fromEntries(new FormData(form).entries());d.salaryUsd=Number(d.salaryUsd)||0;d.tags=d.tags.split(',').map(function(x){return x.trim()}).filter(Boolean);d.published=form.elements.published.checked;post('jobs/save',d).then(function(){dlg.close();note('Vacancy saved');openView('jobs')}).catch(function(x){note(x.message,true)})});
api('session').then(function(r){csrf=r.csrf;showDash()}).catch(showLogin);
})();
}

(() => {
  'use strict';
  const $ = (s, root = document) => root.querySelector(s);
  const state = { csrf: '', view: 'overview', data: {}, query: '', filter: 'all' };
  const meta = {
    overview: ['پوختە', 'دۆخی ئێستای دامەزراندن و کەیسەکان.'],
    jobs: ['هەلی کار', 'هەلی کار دروست، بڵاو و دووبارە بکەرەوە.'],
    applications: ['داواکارییەکان', 'داواکارییەکانی کاندیدەکان بپشکنە و بەڕێوەببە.'],
    clients: ['کڕیار و کەیسەکان', 'گەشتی کڕیار و هەنگاوی داهاتوو بەدواداچوون بکە.'],
    reviews: ['هەڵسەنگاندنەکان', 'پێش بڵاوکردنەوە، بۆچوونەکان پەسەند بکە.'],
    images: ['وێنە سەرەکییەکان', 'وێنە باربکە، ڕیزبەندی و پیشاندان کۆنترۆڵ بکە.'],
    system: ['سیستەم و پاشەکەوت', 'دۆخی سیستەم ببینە و پاشەکەوتێکی تەواو دابگرە.']
  };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const label = value => String(value || '').replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase());

  async function api(path, options = {}) {
    options.headers = {...(options.headers || {}), Accept: 'application/json'};
    if (options.method && options.method !== 'GET') options.headers['X-CSRF-Token'] = state.csrf;
    const response = await fetch('/admin/api/' + path, options);
    const body = await response.json().catch(() => ({error: 'The server returned an unreadable response.'}));
    if (response.status === 401 && path !== 'login') showLogin();
    if (!response.ok || body.ok === false) throw new Error(body.error || 'That action could not be completed.');
    return body;
  }
  const post = (path, data) => api(path, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(data || {})});
  function notice(message, bad = false) {
    const el = $('#notice'); el.textContent = message; el.hidden = false; el.classList.toggle('is-error', bad);
    clearTimeout(el._timer); el._timer = setTimeout(() => el.hidden = true, 4000);
  }
  function showLogin() { $('#dashboard').hidden = true; $('#login').hidden = false; state.csrf = ''; }
  function showDashboard() { $('#login').hidden = true; $('#dashboard').hidden = false; openView(state.view); }
  function loading() { $('#content').innerHTML = '<div class="loading"><i></i><span>چاوەڕوان بە…</span></div>'; }

  $('#login-form').addEventListener('submit', async event => {
    event.preventDefault(); const button = event.currentTarget.querySelector('button'); const error = $('#login-error');
    error.hidden = true; button.disabled = true; button.textContent = 'چوونەژوورەوە…';
    try { const result = await api('login', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({password:$('#password').value})}); state.csrf = result.csrf; $('#password').value = ''; showDashboard(); }
    catch (e) { error.textContent = e.message === 'dashboard_not_configured' ? 'The dashboard password is not configured on the server.' : e.message; error.hidden = false; }
    finally { button.disabled = false; button.textContent = 'چوونەژوورەوە'; }
  });
  $('#logout').addEventListener('click', () => post('logout').finally(showLogin));
  $('#nav').addEventListener('click', event => { const button = event.target.closest('[data-view]'); if (button) { state.view = button.dataset.view; state.query = ''; state.filter = 'all'; openView(state.view); } });

  function configureHeader() {
    document.querySelectorAll('[data-view]').forEach(b => b.classList.toggle('is-active', b.dataset.view === state.view));
    $('#title').textContent = meta[state.view][0]; $('#view-description').textContent = meta[state.view][1];
    const primary = $('#primary-action'); primary.hidden = !['jobs','clients','images'].includes(state.view);
    primary.textContent = state.view === 'jobs' ? '+ هەلی کاری نوێ' : state.view === 'clients' ? '+ کڕیاری نوێ' : '↑ بارکردنی وێنە';
    primary.onclick = () => state.view === 'jobs' ? editJob() : state.view === 'clients' ? editClient() : $('#hero-upload').click();
    $('#export-action').hidden = !['jobs','applications','clients','reviews'].includes(state.view);
  }
  async function openView(view) {
    configureHeader(); loading();
    try {
      if (view === 'overview') return await loadOverview();
      if (view === 'system') return await loadSystem();
      const result = await api(view); state.data[view] = result.data; renderWorkspace();
    } catch (e) { $('#content').innerHTML = '<div class="empty">نەتوانرا ئەم بەشە باربکرێت.</div>'; notice(e.message, true); }
  }
  const metric = (value, title, detail, icon, tone='') => `<article class="metric ${tone}"><span class="metric__icon">${icon}</span><strong>${esc(value)}</strong><span>${esc(title)}</span><small>${esc(detail)}</small></article>`;
  async function loadOverview() {
    const [summary, jobs, apps, clients] = await Promise.all([api('summary'), api('jobs'), api('applications'), api('clients')]);
    state.data.jobs = jobs.data; state.data.applications = apps.data; state.data.clients = clients.data;
    const s = summary.data; const countries = {};
    apps.data.forEach(a => { const country = a.jobCountry || 'هی تر'; countries[country] = (countries[country] || 0) + 1; });
    const top = Object.entries(countries).sort((a,b) => b[1]-a[1]).slice(0,5); const max = top[0]?.[1] || 1;
    $('#content').innerHTML = `<div class="overview-grid">${metric(s.liveJobs,'هەلی کاری بڵاوکراوە',`${s.jobs-s.liveJobs} ڕەشنووس`,'◫','tone-green')}${metric(s.pendingApplications,'داواکاریی نوێ',`${s.applications} کۆی گشتی`,'↗','tone-cyan')}${metric(s.clients,'کەیسی چالاکی کڕیار',`${s.approvedClients || 0} پەسەندکراو`,'◎','tone-blue')}${metric(s.pendingReviews,'هەڵسەنگاندنی چاوەڕوان',`${s.reviews} کۆی گشتی`,'★','tone-gold')}</div>
      <div class="overview-columns"><section class="panel"><div class="panel__head"><h2>نوێترین داواکارییەکان</h2><button class="text-btn" data-go="applications">هەمووی ببینە ←</button></div>${appsTable(apps.data.slice(0,5))}</section>
      <aside><section class="panel"><div class="panel__head"><h2>شوێنی داواکارییەکان</h2></div><div class="bars">${top.length ? top.map(([name,count]) => `<div><span>${esc(name)}</span><b>${count}</b><i style="--w:${count/max*100}%"></i></div>`).join('') : '<p class="sub">هێشتا داتای شوێن نییە.</p>'}</div></section>
      <section class="panel quick-actions"><div class="panel__head"><h2>کردارە خێراکان</h2></div><button data-quick="job">＋ زیادکردنی هەلی کار</button><button data-quick="client">＋ زیادکردنی کەیسی کڕیار</button><button data-go="reviews">✓ پشکنینی هەڵسەنگاندنەکان</button></section></aside></div>`;
  }
  async function loadSystem() {
    const result=await api('diagnostics'), d=result.data;
    $('#content').innerHTML=`<div class="overview-grid">${metric(d.storagePersistent?'بەردەوام':'کاتی','شوێنی هەڵگرتن',d.dataDirectory,'◉',d.storagePersistent?'tone-green':'tone-gold')}${metric(d.telegramConfigured?'چالاکە':'ناچالاکە','بۆتی تێلیگرام',`${d.adminCount} بەڕێوەبەر`,'✈','tone-cyan')}${metric(`${d.sessionHours} کاتژمێر`,'ماوەی دانیشتن','پاشان چوونەژوورەوە پێویستە','⌁','tone-blue')}${metric(`${d.maxUploadMb} MB`,'سنووری بارکردن',d.serverTime,'↑','tone-green')}</div><section class="panel system-tools"><div class="panel__head"><h2>ئامرازەکانی پاراستن</h2></div><div><h3>پاشەکەوتی تەواوی داتا</h3><p>هەموو هەلی کار، داواکاری، کڕیار، هەڵسەنگاندن و وێنە سەرەکییەکان لە فایلێکی JSON دابگرە.</p><button class="btn btn--primary" data-backup>داگرتنی پاشەکەوت</button></div><div><h3>تاقیکردنەوەی ماڵپەڕ</h3><p>ماڵپەڕە گشتییەکە لە پەڕەیەکی نوێدا بکەرەوە و گۆڕانکارییەکان بپشکنە.</p><a class="btn" href="/" target="_blank" rel="noopener">کردنەوەی ماڵپەڕ ↗</a></div></section>`;
  }

  function filteredRows() {
    let rows = state.data[state.view] || []; const q = state.query.toLowerCase();
    if (q) rows = rows.filter(row => JSON.stringify(row).toLowerCase().includes(q));
    if (state.filter !== 'all') rows = rows.filter(row => {
      if (state.view === 'jobs' || state.view === 'reviews') return state.filter === 'live' ? row.published : !row.published;
      if (state.view === 'applications') return state.filter === 'handled' ? row.converted : !row.converted;
      if (state.view === 'clients') return row.status === state.filter;
      if (state.view === 'images') return state.filter === 'live' ? row.published !== false : row.published === false;
      return true;
    }); return rows;
  }
  function filterOptions() {
    const options = {jobs:[['all','هەموو هەلی کارەکان'],['live','بڵاوکراوە'],['draft','ڕەشنووس']],applications:[['all','هەموو داواکارییەکان'],['new','نوێ'],['handled','مامەڵەکراو']],clients:[['all','هەموو کەیسەکان'],['review','لە ژێر پێداچوونەوە'],['action','پێویستی بە بەڵگەنامەیە'],['approved','پەسەندکراو'],['issued','دەرکراو']],reviews:[['all','هەموو هەڵسەنگاندنەکان'],['live','بڵاوکراوە'],['draft','چاوەڕوان']],images:[['all','هەموو وێنەکان'],['live','دیارە'],['draft','شاردراوەتەوە']]}[state.view];
    return options.map(([v,t]) => `<option value="${v}" ${state.filter===v?'selected':''}>${t}</option>`).join('');
  }
  function renderWorkspace() {
    const rows = filteredRows(); const noun = meta[state.view][0].toLowerCase();
    const bulk=['jobs','applications'].includes(state.view)?`<div class="bulk-bar"><span>کرداری کۆمەڵەیی:</span><select id="bulk-operation"><option value="">هەڵبژێرە</option><option value="enable">چالاککردن / بڵاوکردنەوە</option><option value="disable">ناچالاککردن / شاردنەوە</option><option value="delete">سڕینەوە</option></select><button class="btn" data-bulk>جێبەجێکردن</button></div>`:'';
    $('#content').innerHTML = `<div class="workspace-bar"><div class="search-wrap"><span>⌕</span><input id="search" class="search" value="${esc(state.query)}" placeholder="گەڕان لە ${esc(noun)}" aria-label="گەڕان"><kbd>/</kbd></div><select id="filter" aria-label="پاڵاوتن">${filterOptions()}</select><span class="result-count">${rows.length} ئەنجام</span></div>${bulk}<section class="panel">${renderTable(state.view, rows)}</section>`;
    $('#search').addEventListener('input', e => { state.query = e.target.value; renderWorkspace(); $('#search').focus(); });
    $('#filter').addEventListener('change', e => { state.filter = e.target.value; renderWorkspace(); });
  }
  const table = (heads, body) => `<div class="table-wrap"><table class="table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div>`;
  function renderTable(view, rows) { if (!rows.length) return '<div class="empty"><strong>هیچ تۆمارێکی گونجاو نەدۆزرایەوە</strong><span>گەڕان یان پاڵاوتنەکە بگۆڕە.</span></div>'; return ({jobs:jobsTable,applications:appsTable,clients:clientsTable,reviews:reviewsTable,images:imagesTable})[view](rows); }
  function jobsTable(rows) { return table(['✓','هەلی کار','شوێن','دۆخ','کردارەکان'], rows.map(j => `<tr><td><input type="checkbox" data-select value="${esc(j.id)}"></td><td><strong>${esc(j.title)}</strong><span class="sub mono">${esc(j.id)} · ${esc(j.salary)}</span></td><td>${esc(j.city)}, ${esc(j.country)}<span class="sub">${esc(j.category)}</span></td><td><span class="pill ${j.published?'':'pill--off'}">${j.published?'بڵاوکراوەتەوە':'ڕەشنووس'}</span></td><td class="actions"><button data-action="job-preview" data-id="${esc(j.id)}">پێشبینین</button><button data-action="job-edit" data-id="${esc(j.id)}">دەستکاری</button><button data-action="job-photo" data-id="${esc(j.id)}">وێنە</button><button data-action="job-copy" data-id="${esc(j.id)}">دووبارەکردنەوە</button><button data-action="job-toggle" data-id="${esc(j.id)}">${j.published?'لابردن لە بڵاوکردنەوە':'بڵاوکردنەوە'}</button><button class="danger" data-action="job-delete" data-id="${esc(j.id)}">سڕینەوە</button></td></tr>`).join('')); }
  function appsTable(rows) { return table(['✓','داواکار','کار','داواکاری','کردارەکان'], rows.map(a => { const ans=a.answers||{}; const details=Object.entries(ans).filter(([,v])=>!String(v).startsWith('data:image')).slice(0,30).map(([k,v])=>`<dt>${esc(label(k))}</dt><dd>${esc(Array.isArray(v)?v.join(', '):v)}</dd>`).join(''); return `<tr><td><input type="checkbox" data-select value="${esc(a.id)}"></td><td><strong>${esc(ans.fullName||a.id)}</strong><span class="sub mono">${esc(a.id)} · ${esc(a.received)}</span></td><td>${esc(a.jobTitle||'داواکاریی کراوە')}<span class="sub">${esc([a.jobCity,a.jobCountry].filter(Boolean).join(', '))}</span></td><td><details class="detail"><summary>کردنەوەی وردەکاری</summary><dl>${details}</dl><span class="sub">وێنەکان: ${esc((a.photoSlots||[]).join(', ')||'نییە')}</span></details></td><td class="actions">${a.converted?'':'<button data-action="app-convert" data-id="'+esc(a.id)+'">دروستکردنی کەیس</button>'}<button data-action="app-toggle" data-id="${esc(a.id)}">${a.converted?'نیشانکردن وەک نوێ':'نیشانکردن وەک مامەڵەکراو'}</button><button class="danger" data-action="app-delete" data-id="${esc(a.id)}">سڕینەوە</button></td></tr>`; }).join('')); }
  function clientsTable(rows) { const status={review:'لە ژێر پێداچوونەوە',action:'پێویستی بە بەڵگەنامەیە',approved:'پەسەندکراو',issued:'دەرکراو'}; return table(['کڕیار','ڕێگای کەیس','دۆخ','کردارەکان'], rows.map(c => `<tr><td><strong>${esc(c.nameEn||c.key)}</strong><span class="sub mono">${esc(c.key)} · ${esc(c.phone||'ژمارە نییە')}</span></td><td>${esc(c.route||'دانەنراوە')}<span class="sub">${esc(c.nationality||'ڕەگەزنامە دانەنراوە')}</span></td><td><span class="pill case--${esc(c.status||'review')}">${esc(status[c.status]||status.review)}</span><span class="sub">${esc(c.note||'تێبینی نییە')}</span></td><td class="actions"><button data-action="client-edit" data-id="${esc(c.key)}">دەستکاری</button><button data-action="client-copy" data-id="${esc(c.key)}">کۆپیکردنی ناسنامە</button><button class="danger" data-action="client-delete" data-id="${esc(c.key)}">سڕینەوە</button></td></tr>`).join('')); }
  function reviewsTable(rows) { return table(['هەڵسەنگێنەر','هەڵسەنگاندن','دۆخ','کردارەکان'], rows.map(r => `<tr><td><strong>${esc(r.name)}</strong><span class="sub mono">${esc(r.id)} · ${esc(r.rating)}/5 ئەستێرە</span></td><td class="review-copy">${esc(r.text)}</td><td><span class="pill ${r.published?'':'pill--off'}">${r.published?'بڵاوکراوەتەوە':'چاوەڕوان'}</span></td><td class="actions"><button data-action="review-toggle" data-id="${esc(r.id)}">${r.published?'شاردنەوە':'بڵاوکردنەوە'}</button><button class="danger" data-action="review-delete" data-id="${esc(r.id)}">سڕینەوە</button></td></tr>`).join('')); }
  function imagesTable(rows) { return table(['پێشبینین','وێنە','دۆخ','ڕیزبەندی و کردار'], rows.map((r,i) => `<tr><td>${r.file?`<img class="thumb" src="/media/${esc(r.file)}" alt="">`:'—'}</td><td><strong>${esc(r.id)}</strong><span class="sub mono">${esc(r.file||'')}</span></td><td><span class="pill ${r.published===false?'pill--off':''}">${r.published===false?'شاردراوەتەوە':'دیارە'}</span></td><td class="actions"><button data-action="image-preview" data-id="${esc(r.id)}">پێشبینین</button><button data-action="image-up" data-id="${esc(r.id)}" ${i===0?'disabled':''}>↑</button><button data-action="image-down" data-id="${esc(r.id)}" ${i===rows.length-1?'disabled':''}>↓</button><button data-action="image-toggle" data-id="${esc(r.id)}">${r.published===false?'پیشاندان':'شاردنەوە'}</button><button class="danger" data-action="image-delete" data-id="${esc(r.id)}">سڕینەوە</button></td></tr>`).join('')); }

  $('#content').addEventListener('click', async event => {
    const backup=event.target.closest('[data-backup]'); if(backup){try{backup.disabled=true;const result=await api('backup');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(result.data,null,2)],{type:'application/json'}));a.download=`aryos-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);notice('پاشەکەوت دابەزێنرا')}catch(e){notice(e.message,true)}finally{backup.disabled=false}return}
    const bulk=event.target.closest('[data-bulk]'); if(bulk){const ids=[...document.querySelectorAll('[data-select]:checked')].map(x=>x.value),operation=$('#bulk-operation')?.value;if(!ids.length||!operation)return notice('تۆمار و کردار هەڵبژێرە.',true);if(operation==='delete'&&!confirm(`دڵنیایت لە سڕینەوەی ${ids.length} تۆمار؟`))return;try{await post('bulk',{kind:state.view,ids,operation});notice('کرداری کۆمەڵەیی جێبەجێ کرا');await openView(state.view)}catch(e){notice(e.message,true)}return}
    const go = event.target.closest('[data-go]'); if (go) { state.view=go.dataset.go; state.query=''; state.filter='all'; return openView(state.view); }
    const quick = event.target.closest('[data-quick]'); if (quick) return quick.dataset.quick==='job' ? editJob() : editClient();
    const button = event.target.closest('[data-action]'); if (!button) return; const id=button.dataset.id, action=button.dataset.action;
    if (action==='job-preview') return previewJob((state.data.jobs||[]).find(x=>x.id===id));
    if (action==='image-preview') return previewImage((state.data.images||[]).find(x=>x.id===id));
    if (action==='job-edit') return editJob((state.data.jobs||[]).find(x=>x.id===id));
    if (action==='job-photo') { $('#job-photo-upload').dataset.id=id; return $('#job-photo-upload').click(); }
    if (action==='client-edit') return editClient((state.data.clients||[]).find(x=>x.key===id));
    if (action==='client-copy') { await navigator.clipboard.writeText(id); return notice('ناسنامەی کڕیار کۆپی کرا'); }
    if (action.includes('delete') && !confirm(`دڵنیایت لە سڕینەوەی ${id}؟ ئەم کردارە ناگەڕێتەوە.`)) return;
    const routes={ 'job-copy':'jobs/duplicate','job-toggle':'jobs/toggle','job-delete':'jobs/delete','app-convert':'applications/convert','app-toggle':'applications/toggle','app-delete':'applications/delete','client-delete':'clients/delete','review-toggle':'reviews/toggle','review-delete':'reviews/delete','image-up':'images/up','image-down':'images/down','image-toggle':'images/toggle','image-delete':'images/delete' };
    button.disabled=true;
    const payload = {id, key:id};
    if (action === 'review-toggle') payload.published = !!(state.data.reviews || []).find(row => row.id === id)?.published;
    try { const result=await post(routes[action], payload); notice(action==='job-copy'?'هەلی کار دووبارە کرایەوە':action==='app-convert'?`کەیسی کڕیار دروست کرا: ${result.data.key}`:'گۆڕانکارییەکان پاشەکەوت کران'); await openView(state.view); }
    catch(e) { button.disabled=false; notice(e.message,true); }
  });

  const jobDialog=$('#job-dialog'), jobForm=$('#job-form');
  function editJob(job={}) { $('#job-heading').textContent=job.id?`دەستکاری ${job.id}`:'هەلی کاری نوێ'; ['id','title','country','city','region','category','salary','salaryUsd','hours','type','desc'].forEach(k=>{if(jobForm.elements[k])jobForm.elements[k].value=job[k]??''}); jobForm.elements.tags.value=(job.tags||[]).join(', '); jobForm.elements.published.checked=job.id?!!job.published:true; jobDialog.showModal(); }
  document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>jobDialog.close()));
  jobForm.addEventListener('submit', async e => { e.preventDefault(); const data=Object.fromEntries(new FormData(jobForm)); data.salaryUsd=Number(data.salaryUsd)||0; data.tags=data.tags.split(',').map(x=>x.trim()).filter(Boolean); data.published=jobForm.elements.published.checked; try { await post('jobs/save',data); jobDialog.close(); notice('هەلی کار پاشەکەوت کرا'); state.view='jobs'; await openView('jobs'); } catch(err){notice(err.message,true)} });
  const clientDialog=$('#client-dialog'), clientForm=$('#client-form');
  function editClient(client={}) { $('#client-heading').textContent=client.key?'دەستکاری کڕیار':'کڕیاری نوێ'; ['key','nameEn','phone','nationality','route','status','dob','education','note','experience'].forEach(k=>{if(clientForm.elements[k])clientForm.elements[k].value=client[k]??''}); clientDialog.showModal(); }
  document.querySelectorAll('[data-client-close]').forEach(b=>b.addEventListener('click',()=>clientDialog.close()));
  clientForm.addEventListener('submit', async e => { e.preventDefault(); try { await post('clients/save',Object.fromEntries(new FormData(clientForm))); clientDialog.close(); notice('کەیسی کڕیار پاشەکەوت کرا'); state.view='clients'; await openView('clients'); } catch(err){notice(err.message,true)} });
  $('#hero-upload').addEventListener('change', async event => { const file=event.target.files[0]; if(!file)return; if(file.size>10*1024*1024){notice('وێنەیەکی کەمتر لە 10 MB هەڵبژێرە.',true);return} const reader=new FileReader(); reader.onload=async()=>{try{await post('images/upload',{name:file.name,data:reader.result});notice('وێنەی سەرەکی بارکرا');state.view='images';await openView('images')}catch(e){notice(e.message,true)}finally{event.target.value=''}};reader.readAsDataURL(file); });
  $('#job-photo-upload').addEventListener('change', async event => { const file=event.target.files[0],id=event.target.dataset.id;if(!file||!id)return;if(file.size>10*1024*1024){notice('وێنەیەکی کەمتر لە 10 MB هەڵبژێرە.',true);return}const reader=new FileReader();reader.onload=async()=>{try{await post('jobs/photo',{id,image:reader.result});notice('وێنەی هەلی کار نوێ کرایەوە');await openView('jobs')}catch(e){notice(e.message,true)}finally{event.target.value=''}};reader.readAsDataURL(file);});
  const previewDialog=$('#preview-dialog');
  function previewJob(job){if(!job)return;$('#preview-title').textContent=job.title;const photo=job.photo?`/media/${esc(job.photo)}`:'';$('#preview-content').innerHTML=`<article class="live-job-preview">${photo?`<img src="${photo}" alt="">`:'<div class="preview-placeholder">وێنە نییە</div>'}<div class="live-job-preview__body"><div><span class="pill ${job.published?'':'pill--off'}">${job.published?'بڵاوکراوەتەوە':'ڕەشنووس'}</span><span class="preview-ref">${esc(job.id)}</span></div><h2>${esc(job.title)}</h2><p class="preview-location">⌖ ${esc(job.city)}، ${esc(job.country)}</p><div class="preview-facts"><span>${esc(job.salary)}</span><span>${esc(job.type||'')}</span><span>${esc(job.hours||'')}</span></div><p>${esc(job.desc||'وەسف دانەنراوە.')}</p><div class="preview-tags">${(job.tags||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div><button class="preview-apply" disabled>داواکردنی ئێستا</button></div></article>`;const link=$('#preview-public-link');link.href=`/jobs.html?q=${encodeURIComponent(job.id)}`;link.hidden=!job.published;previewDialog.showModal()}
  function previewImage(item){if(!item)return;$('#preview-title').textContent=item.id;$('#preview-content').innerHTML=`<div class="live-hero-preview"><img src="/media/${esc(item.file||'')}" alt=""><div class="live-hero-copy"><small>گروپی ئاریۆس — دامەزراندنی نێودەوڵەتی</small><h2>دەرفەت سنووری نییە.</h2><p>بە پشتیوانی ئاریۆس، کار و داهاتووی نوێ بدۆزەرەوە.</p><span class="pill ${item.published===false?'pill--off':''}">${item.published===false?'شاردراوەتەوە':'لە ماڵپەڕدا دیارە'}</span></div></div>`;const link=$('#preview-public-link');link.href='/';link.hidden=false;previewDialog.showModal()}
  document.querySelectorAll('[data-preview-close]').forEach(b=>b.addEventListener('click',()=>previewDialog.close()));

  const searchDialog=$('#global-search-dialog'), globalInput=$('#global-search'), globalResults=$('#global-search-results');
  async function openGlobalSearch(){searchDialog.showModal();globalInput.value='';globalResults.innerHTML='<div class="loading search-loading"><i></i><span>داتا بار دەکرێت…</span></div>';globalInput.focus();try{const names=['jobs','applications','clients','reviews','images'];const missing=names.filter(n=>!state.data[n]);const loaded=await Promise.all(missing.map(n=>api(n)));missing.forEach((n,i)=>state.data[n]=loaded[i].data);globalResults.innerHTML='<div class="empty">دەست بە نووسین بکە بۆ گەڕان لە هەموو داتاکان.</div>'}catch(e){globalResults.innerHTML='<div class="empty">گەڕان ئامادە نەکرا.</div>';notice(e.message,true)}}
  function searchAll(query){const q=query.trim().toLowerCase();if(q.length<2){globalResults.innerHTML='<div class="empty">لانیکەم دوو پیت بنووسە.</div>';return}const configs={jobs:['هەلی کار',x=>[x.title,x.id,x.city,x.country,x.category,x.salary]],applications:['داواکاری',x=>[x.id,x.jobTitle,x.jobCity,x.jobCountry,...Object.values(x.answers||{})]],clients:['کڕیار و کەیس',x=>[x.key,x.nameEn,x.phone,x.nationality,x.route,x.note]],reviews:['هەڵسەنگاندن',x=>[x.id,x.name,x.text,x.rating]],images:['وێنە',x=>[x.id,x.file]]};let html='',total=0;Object.entries(configs).forEach(([view,[title,fields]])=>{const matches=(state.data[view]||[]).filter(x=>fields(x).flat().join(' ').toLowerCase().includes(q)).slice(0,6);if(!matches.length)return;total+=matches.length;html+=`<section><h3>${title}<span>${matches.length}</span></h3>${matches.map(x=>{const id=x.id||x.key;const primary=x.title||x.nameEn||x.name||x.jobTitle||x.id;const secondary=view==='jobs'?`${x.city}، ${x.country}`:view==='applications'?(x.answers?.fullName||x.id):view==='clients'?(x.phone||x.route||x.key):view==='reviews'?`${x.rating}/5`:x.file;return`<button data-global-view="${view}" data-global-query="${esc(id)}"><span class="global-icon">${{jobs:'◫',applications:'↗',clients:'◎',reviews:'★',images:'▧'}[view]}</span><span><strong>${esc(primary)}</strong><small>${esc(secondary||id)}</small></span><code>${esc(id)}</code></button>`}).join('')}</section>`});globalResults.innerHTML=total?html:'<div class="empty"><strong>هیچ ئەنجامێک نەدۆزرایەوە</strong><span>وشەیەکی تر تاقی بکەرەوە.</span></div>'}
  $('#global-search-action').addEventListener('click',openGlobalSearch);globalInput.addEventListener('input',e=>searchAll(e.target.value));globalResults.addEventListener('click',e=>{const row=e.target.closest('[data-global-view]');if(!row)return;searchDialog.close();state.view=row.dataset.globalView;state.query=row.dataset.globalQuery;state.filter='all';openView(state.view)});searchDialog.addEventListener('click',e=>{if(e.target===searchDialog)searchDialog.close()});
  $('#export-action').addEventListener('click', () => { const rows=filteredRows(); if(!rows.length)return notice('هیچ شتێک بۆ هەناردەکردن نییە.',true); const keys=[...new Set(rows.flatMap(Object.keys))].filter(k=>!['answers','photoSlots'].includes(k)); const csv=[keys,...rows.map(row=>keys.map(k=>Array.isArray(row[k])?row[k].join('; '):typeof row[k]==='object'?JSON.stringify(row[k]??''):row[k]??''))].map(line=>line.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\r\n'); const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download=`aryos-${state.view}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href); });
  document.addEventListener('keydown', e => { if(e.key==='Escape'){jobDialog.close();clientDialog.close()} if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openGlobalSearch()} if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)){e.preventDefault();$('#search')?.focus()} if(e.key.toLowerCase()==='n'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)){if(state.view==='jobs')editJob();if(state.view==='clients')editClient()} });
  api('session').then(result=>{state.csrf=result.csrf;showDashboard()}).catch(showLogin);
})();
